steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         '-d',
         '--name import-publisher-container',
         'gcr.io/google.com/datcom-data/import-publisher-image']
- name: 'gcr.io/cloud-builders/docker'
  args: ['cp',
         'import-publisher-container:/import-publisher',
         'import-publisher']
- name: 'gcr.io/cloud-builders/docker'
  args: ['stop',
         'import-publisher-container']
- name: 'python:3-slim'
  args: ['pip3',
         'install',
         '--no-cache-dir',
         '-r',
         'import-publisher/requirements.txt']
- name: 'python:3-slim'
  args: ['python3',
         'import-publisher/main.py']
